# Generated by Django 4.2.3 on 2023-08-12 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('jersey_number', models.PositiveIntegerField()),
                ('birthdate', models.DateField()),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roster_manager.position')),
            ],
        ),
    ]
