# Generated by Django 4.2.3 on 2023-08-13 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='batting_throwing',
            field=models.CharField(default='L/R', max_length=10),
        ),
        migrations.AddField(
            model_name='player',
            name='class_standing',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='player',
            name='height',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='player',
            name='home_runs',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='hometown',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='pitching_records',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='avg',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='school',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='weight',
            field=models.CharField(default='N/A', max_length=10),
        ),
    ]
