# Generated by Django 4.2.3 on 2023-08-13 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roster_manager', '0002_player_batting_throwing_player_class_standing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='pitching_records',
        ),
        migrations.AddField(
            model_name='player',
            name='era',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='pitching_losses',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='pitching_wins',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='batting_throwing',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='player',
            name='class_standing',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='hometown',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roster_manager.position'),
        ),
        migrations.AlterField(
            model_name='player',
            name='school',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.PositiveIntegerField(),
        ),
    ]
