# Generated by Django 4.2.3 on 2023-08-13 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster_manager', '0004_alter_player_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='avg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
    ]
